simplify options

diff --git a/qmolpro b/qmolpro
--- a/qmolpro
+++ b/qmolpro
@@ -1,18 +1,24 @@
 #!/bin/sh
-prog=`basename $0`
-prog=${prog#q}
+prefix='q'
+this=`basename $0`
+prog=${this#${prefix}}
 
+# configuration
+#Include this if workers have different core count to head, or if you want for other reasons to configure manually
+#maxtasks_per_node=16 
 
-maxtasks_per_node=16 ; maxcpus=4096 ; cpus=$maxtasks_per_node ;
-# defaults
-NODETYPE=${NODETYPE:-i686}
-WALLTIME=1
-tasks_per_node=$maxtasks_per_node
+if [ -z "$maxtasks_per_node" ]; then uname=$(uname); test $uname = Darwin && max_tasks_per_node=$(sysctl -n hw.ncpu) || maxtasks_per_node=$(nproc||echo 1) ; fi
+echo max_tasks_per_node=$max_tasks_per_node
+
+#default
+defaultoptions="-n $max_tasks_per_node"
                                                                                 
 # parse options
-set -- `getopt gvW:n:l:q:P: $*`
+configfileoptions=$(cat ${HOME}/.${this}rc)
+set -- `getopt gvW:n:l:q:P: $defaultoptions $configfileoptions $*`
 parse_opts=0
 while [ "$1" != -- ]; do
+    echo option $1
   case "$1" in
     -g) debug=1 ;;
     -v) verbose=1 ;;
@@ -28,34 +34,26 @@ while [ "$1" != -- ]; do
 done
 shift
 
-if [ "x$QUEUE" = "xserial" ]; then
-  max_tasks_per_node=1
-  cpus=1
-fi
+
+# if [ x${PROJECT} == x ]; then
+#   echo "Project missing. Specify it with -P (possible in $HOME/.${this}rc), or via the PROJECT environment variable"
+#   exit 1;
+# fi
 
 tasks_per_node=$maxtasks_per_node
-
-if [ x${PROJECT} == x ]; then
-  echo "Project missing. Specify it with -P, or via the PROJECT environment variable"
-  exit 1;
+cpus=`echo $NOPTION | sed -e 's/\/.*$//'`
+tasks_per_node=`echo $NOPTION | sed -e 's/^.*\///' -e 's/:.*$//'`
+if [ $tasks_per_node -eq $cpus ]; then
+    task_flag="total"
+    tasks_per_node=$maxtasks_per_node
+elif [ $tasks_per_node -gt $maxtasks_per_node ]; then
+    echo TASKS_PER_NODE too high, ignoring
+    task_flag="total"
+    tasks_per_node=$maxtasks_per_node
 fi
-
-if [ x${NOPTION} != x ]; then
-  cpus=`echo $NOPTION | sed -e 's/\/.*$//'`
-  tasks_per_node=`echo $NOPTION | sed -e 's/^.*\///' -e 's/:.*$//'`
-  if [ $tasks_per_node -eq $cpus ]; then
-   task_flag="total"
-   tasks_per_node=$maxtasks_per_node
-  elif [ $tasks_per_node -gt $maxtasks_per_node ]; then
-   echo TASKS_PER_NODE too high, ignoring
-   task_flag="total"
-   tasks_per_node=$maxtasks_per_node
-  fi
-fi
-#tasks_per_node=2
-if [ $cpus -gt $maxcpus ] ; then echo Too many cpus ; parse_opts=1 ; fi
 typeset -i nodes
 let nodes=($cpus-1)/$tasks_per_node+1;
+if [ $nodes -eq 1 ]; then tasks_per_node=$cpus; fi
  
 if [ $parse_opts -eq 1 ] ; then
 cat << EOF
@@ -64,7 +62,6 @@ EOF
 exit 1
 fi
 
-if [ $cpus -eq 1 ]; then tasks_per_node=1; fi
 
 if [ ! -z $verbose ]; then
 echo 'Processors:      ' $cpus
@@ -72,7 +69,7 @@ echo 'Tasks per node:  ' $tasks_per_node
 echo 'Nodes:           ' $nodes
 fi;
 
-if [ "x$QUEUE" != "xserial" ]; then
+if [ "x$cpus" != "x1" ]; then
   QSUBARGS="$QSUBARGS -l select=${nodes}:ncpus=${tasks_per_node}:mpiprocs=${tasks_per_node} "
 fi
 
@@ -85,7 +82,6 @@ jobname=`basename ${file}|sed -e 's/\.[a-zA-Z0-9]*$//'`
 qjobname=`echo "$jobname" | sed -e 's,[-+.],,g' -e 's,\(..........\).*,\1,'`
 echo qsub $QSUBARGS -j oe -N ${qjobname} -P $PROJECT
 qsub $QSUBARGS -j oe -N ${qjobname} -P $PROJECT << EOF
-#PBS -l place=scatter:excl
 
 if [ -r .bashrc ]; then  . .bashrc ; fi
 export MOLPRO_OPTIONS="$MOLPRO_OPTIONS"
